# Generated by Django 2.1.4 on 2018-12-24 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ism', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FetchItem',
        ),
    ]
