# Generated by Django 2.1.4 on 2018-12-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ism', '0003_fetchitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchitem',
            name='num_rows',
            field=models.IntegerField(default=0),
        ),
    ]
