# Generated by Django 2.1.4 on 2018-12-26 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ism', '0006_searchdoc_searchindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchdoc',
            name='doc_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='searchdoc',
            name='searchindex_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
