# Generated by Django 2.1.4 on 2018-12-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IsmRelInvVioD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_rel_inq_idn', models.IntegerField()),
                ('f_rel_inv_idn', models.IntegerField()),
                ('f_inv_vio_srn', models.IntegerField()),
                ('f_del_cde', models.CharField(max_length=3, null=True)),
                ('f_edt_day', models.CharField(max_length=8, null=True)),
                ('f_edt_dtm', models.DateTimeField(null=True)),
                ('f_edt_ocp_cde', models.CharField(max_length=5, null=True)),
                ('f_edt_prt_cde', models.CharField(max_length=4, null=True)),
                ('f_exp_day', models.CharField(max_length=8, null=True)),
                ('f_inv_acm_cde', models.CharField(max_length=5, null=True)),
                ('f_inv_dtl', models.CharField(max_length=1000, null=True)),
                ('f_ivd_cde', models.CharField(max_length=3, null=True)),
                ('f_ivd_day', models.CharField(max_length=8, null=True)),
                ('f_ivd_ocp_cde', models.CharField(max_length=5, null=True)),
                ('f_ivd_opr_day', models.CharField(max_length=8, null=True)),
                ('f_ivd_opr_num', models.CharField(max_length=20, null=True)),
                ('f_ivd_prt_cde', models.CharField(max_length=4, null=True)),
                ('f_ivd_rsn_cde', models.CharField(max_length=3, null=True)),
                ('f_law_cde', models.CharField(max_length=3, null=True)),
                ('f_law_knd_cde', models.CharField(max_length=3, null=True)),
                ('f_law_vio_dtl', models.CharField(max_length=1000, null=True)),
                ('f_reg_day', models.CharField(max_length=8, null=True)),
                ('f_reg_ocp_cde', models.CharField(max_length=5, null=True)),
                ('f_reg_prt_cde', models.CharField(max_length=4, null=True)),
                ('f_vio_ctn', models.CharField(max_length=1000, null=True)),
                ('f_vio_day', models.CharField(max_length=8, null=True)),
                ('f_vio_dtl', models.CharField(max_length=1000, null=True)),
                ('f_vio_opn', models.CharField(max_length=1000, null=True)),
                ('f_vio_opr_day', models.CharField(max_length=8, null=True)),
                ('f_vio_opr_num', models.CharField(max_length=50, null=True)),
                ('f_vio_pla', models.CharField(max_length=200, null=True)),
                ('f_vio_rsn_cde', models.CharField(max_length=3, null=True)),
            ],
            options={
                'db_table': 'ISM_T_REL_INV_VIO_D',
            },
        ),
    ]
