# Generated by Django 2.1.4 on 2018-12-17 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_syncmodel_is_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syncmodelcolumns',
            old_name='enabled',
            new_name='is_enabled',
        ),
    ]
