# Generated by Django 2.1.4 on 2018-12-17 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_auto_20181218_0627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syncmodelcolumns',
            old_name='modelsync',
            new_name='syncmodel',
        ),
    ]
