# Generated by Django 2.1.4 on 2018-12-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_ismrelletd'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsmRelInvM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_aln_idn', models.IntegerField(null=True)),
                ('f_aln_psp_idn', models.IntegerField(null=True)),
                ('f_dom_idn', models.IntegerField(null=True)),
                ('f_dom_psp_idn', models.IntegerField(null=True)),
                ('f_rel_inq_idn', models.IntegerField(null=True)),
                ('f_sty_idn', models.IntegerField(null=True)),
                ('f_vsa_idn', models.IntegerField(null=True)),
                ('f_rel_inv_idn', models.IntegerField()),
                ('f_dcs_day', models.CharField(max_length=8, null=True)),
                ('f_dcs_ocp_cde', models.CharField(max_length=5, null=True)),
                ('f_dcs_prs_cde', models.CharField(max_length=3, null=True)),
                ('f_del_cde', models.CharField(max_length=3, null=True)),
                ('f_doa_cde', models.CharField(max_length=3, null=True)),
                ('f_edt_day', models.CharField(max_length=8, null=True)),
                ('f_edt_dtm', models.DateTimeField(null=True)),
                ('f_edt_ocp_cde', models.CharField(max_length=5, null=True)),
                ('f_edt_prt_cde', models.CharField(max_length=4, null=True)),
                ('f_inv_ara_cde', models.CharField(max_length=4, null=True)),
                ('f_inv_cti', models.CharField(max_length=50, null=True)),
                ('f_inv_cty_cde', models.CharField(max_length=3, null=True)),
                ('f_inv_day', models.CharField(max_length=8, null=True)),
                ('f_inv_dtl', models.CharField(max_length=200, null=True)),
                ('f_inv_kur', models.CharField(max_length=100, null=True)),
                ('f_inv_ocp_cde', models.CharField(max_length=5, null=True)),
                ('f_inv_prs_cde', models.CharField(max_length=3, null=True)),
                ('f_inv_vrf_cde', models.CharField(max_length=5, null=True)),
                ('f_ivd_cde', models.CharField(max_length=3, null=True)),
                ('f_ivd_day', models.CharField(max_length=8, null=True)),
                ('f_ivd_ocp_cde', models.CharField(max_length=5, null=True)),
                ('f_ivd_opr_day', models.CharField(max_length=8, null=True)),
                ('f_ivd_opr_num', models.CharField(max_length=20, null=True)),
                ('f_ivd_prt_cde', models.CharField(max_length=4, null=True)),
                ('f_ivd_rsn_cde', models.CharField(max_length=3, null=True)),
                ('f_mak_day', models.CharField(max_length=8, null=True)),
                ('f_mak_ocp_cde', models.CharField(max_length=5, null=True)),
                ('f_mak_prs_cde', models.CharField(max_length=3, null=True)),
                ('f_reg_day', models.CharField(max_length=8, null=True)),
                ('f_reg_ocp_cde', models.CharField(max_length=5, null=True)),
                ('f_reg_pla', models.CharField(max_length=200, null=True)),
                ('f_reg_prt_cde', models.CharField(max_length=4, null=True)),
            ],
            options={
                'db_table': 'ISM_T_REL_INV_M',
            },
        ),
    ]
