# Generated by Django 2.1.4 on 2018-12-19 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0010_ismrelinvm'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_ms', models.IntegerField()),
                ('stopped_at', models.DateTimeField(auto_now_add=True)),
                ('sync_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='entities.SyncModel')),
            ],
        ),
        migrations.AddField(
            model_name='ismrelinvm',
            name='change_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ismrelinvm',
            name='row_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ismrelinvviod',
            name='change_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ismrelinvviod',
            name='row_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ismrelletd',
            name='change_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ismrelletd',
            name='row_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
