# Generated by Django 2.1.4 on 2018-12-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0011_auto_20181219_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ismrelinvm',
            name='change_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='ismrelinvviod',
            name='change_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='ismrelletd',
            name='change_id',
            field=models.BigIntegerField(),
        ),
    ]
