# Generated by Django 2.1.4 on 2018-12-19 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0014_gracefulerrors'),
    ]

    operations = [
        migrations.AddField(
            model_name='gracefulerrors',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
