# Generated by Django 2.1.4 on 2018-12-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0015_gracefulerrors_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gracefulerrors',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
