# Generated by Django 2.1.4 on 2018-12-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0016_gracefulerrors_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ismrelinvviod',
            name='change_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ismrelinvviod',
            name='f_inv_vio_srn',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ismrelinvviod',
            name='f_rel_inq_idn',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ismrelinvviod',
            name='f_rel_inv_idn',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ismrelinvviod',
            name='row_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
