# Generated by Django 2.1.4 on 2018-12-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0017_auto_20181220_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncmodel',
            name='last_change_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
