# Generated by Django 2.1.4 on 2018-12-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0018_syncmodel_last_change_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncstatus',
            name='num_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syncstatus',
            name='num_duplicates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syncstatus',
            name='num_fetch_expected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syncstatus',
            name='num_fetched',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syncstatus',
            name='num_updated',
            field=models.IntegerField(default=0),
        ),
    ]
