# Generated by Django 2.1.4 on 2018-12-21 02:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0019_auto_20181221_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncmodel',
            name='last_sync_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
