# Generated by Django 2.1.4 on 2018-12-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0021_auto_20181222_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncmodelcolumn',
            name='aggregation',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
