# Generated by Django 2.1.4 on 2018-12-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0022_syncmodelcolumn_aggregation'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsmPspAlnM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_id', models.IntegerField(db_index=True)),
                ('row_id', models.CharField(db_index=True, max_length=50)),
                ('f_aln_idn', models.IntegerField(null=True)),
                ('f_aln_psp_idn', models.IntegerField(db_index=True)),
                ('f_bir_day', models.CharField(max_length=8, null=True)),
                ('f_fnm_gnr', models.CharField(max_length=50, null=True)),
                ('f_fnm_nam', models.CharField(max_length=50, null=True)),
                ('f_gen_cde', models.CharField(max_length=3, null=True)),
                ('f_ntl_cde', models.CharField(max_length=3, null=True)),
                ('f_psp_num', models.CharField(max_length=40, null=True)),
                ('f_abb_nam', models.CharField(max_length=10, null=True)),
                ('f_all_nam', models.CharField(max_length=100, null=True)),
                ('f_ccl_yon_cde', models.CharField(max_length=3, null=True)),
                ('f_crw_idn', models.IntegerField(null=True)),
                ('f_dbl_reg_rsn', models.CharField(max_length=10, null=True)),
                ('f_del_cde', models.CharField(max_length=3, null=True)),
                ('f_edt_day', models.CharField(max_length=8, null=True)),
                ('f_edt_dtm', models.DateTimeField(null=True)),
                ('f_edt_ocp_cde', models.CharField(max_length=5, null=True)),
                ('f_edt_prt_cde', models.CharField(max_length=4, null=True)),
                ('f_epr_day', models.CharField(max_length=8, null=True)),
                ('f_etr_uyn_cde', models.CharField(max_length=3, null=True)),
                ('f_fnm_trb', models.CharField(max_length=50, null=True)),
                ('f_isc_iss_cpn', models.CharField(max_length=100, null=True)),
                ('f_isc_ntl_cde', models.CharField(max_length=3, null=True)),
                ('f_isc_rsd_num', models.CharField(max_length=20, null=True)),
                ('f_iss_day', models.CharField(max_length=8, null=True)),
                ('f_ivd_cde', models.CharField(max_length=3, null=True)),
                ('f_ivd_day', models.CharField(max_length=8, null=True)),
                ('f_ivd_ocp_cde', models.CharField(max_length=5, null=True)),
                ('f_ivd_prt_cde', models.CharField(max_length=4, null=True)),
                ('f_lev_uyn_cde', models.CharField(max_length=3, null=True)),
                ('f_psp_clf_cde', models.CharField(max_length=3, null=True)),
                ('f_psp_knd_cde', models.CharField(max_length=3, null=True)),
                ('f_psp_pic', models.BinaryField(null=True)),
                ('f_psp_typ_cde', models.CharField(max_length=3, null=True)),
                ('f_psp_use_cut', models.IntegerField(null=True)),
                ('f_reg_day', models.CharField(max_length=8, null=True)),
                ('f_reg_ocp_cde', models.CharField(max_length=5, null=True)),
                ('f_reg_prt_cde', models.CharField(max_length=4, null=True)),
                ('f_rsd_num_eng', models.CharField(max_length=16, null=True)),
                ('f_rsd_num_mga', models.CharField(max_length=16, null=True)),
                ('f_sgl_yon_cde', models.CharField(max_length=3, null=True)),
            ],
            options={
                'db_table': 'ISM_T_PSP_ALN_M',
            },
        ),
    ]
