# Generated by Django 2.1.4 on 2018-12-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0023_ismpspalnm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncmodel',
            name='last_sync_at',
            field=models.DateTimeField(null=True),
        ),
    ]
