# Generated by Django 2.1.4 on 2018-12-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0025_auto_20181223_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsmAlnM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_id', models.BigIntegerField(db_index=True)),
                ('row_id', models.CharField(db_index=True, max_length=50)),
                ('f_aln_idn', models.IntegerField(db_index=True)),
                ('f_bir_day', models.CharField(max_length=8, null=True)),
                ('f_fnm_gnr', models.CharField(max_length=50, null=True)),
                ('f_fnm_nam', models.CharField(max_length=50, null=True)),
                ('f_gen_cde', models.CharField(max_length=3, null=True)),
                ('f_ntl_cde', models.CharField(max_length=3, null=True)),
                ('f_dbl_nyn_cde', models.CharField(max_length=3, null=True)),
                ('f_del_cde', models.CharField(max_length=3, null=True)),
                ('f_edt_day', models.CharField(max_length=8, null=True)),
                ('f_edt_dtm', models.DateTimeField(null=True)),
                ('f_edt_ocp_cde', models.CharField(max_length=5, null=True)),
                ('f_edt_prt_cde', models.CharField(max_length=4, null=True)),
                ('f_fnm_trb', models.CharField(max_length=50, null=True)),
                ('f_ivd_cde', models.CharField(max_length=3, null=True)),
                ('f_ivd_day', models.CharField(max_length=8, null=True)),
                ('f_ivd_ocp_cde', models.CharField(max_length=5, null=True)),
                ('f_ivd_prt_cde', models.CharField(max_length=4, null=True)),
                ('f_mga_nyn_cde', models.CharField(max_length=3, null=True)),
                ('f_reg_day', models.CharField(max_length=8, null=True)),
                ('f_reg_ocp_cde', models.CharField(max_length=5, null=True)),
                ('f_reg_prt_cde', models.CharField(max_length=4, null=True)),
                ('f_rsd_num_eng', models.CharField(max_length=16, null=True)),
                ('f_rsd_num_mga', models.CharField(max_length=16, null=True)),
            ],
            options={
                'db_table': 'ISM_T_ALN_M',
            },
        ),
    ]
