# Generated by Django 2.1.4 on 2018-12-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0027_ismintacmd_ismintjdgd_ismintm_ismintrecm_ismntldblm_ismntlgetattd_ismntlgetjdgd_ismntlgetm_ismntlget'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsmToadPlanTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_id', models.BigIntegerField(db_index=True)),
                ('row_id', models.CharField(db_index=True, max_length=50)),
                ('f_access_predicates', models.TextField(null=True)),
                ('f_bytes', models.IntegerField(null=True)),
                ('f_cardinality', models.IntegerField(null=True)),
                ('f_cost', models.IntegerField(null=True)),
                ('f_cpu_cost', models.IntegerField(null=True)),
                ('f_depth', models.IntegerField(null=True)),
                ('f_distribution', models.CharField(max_length=30, null=True)),
                ('f_filter_predicates', models.TextField(null=True)),
                ('f_id', models.IntegerField(null=True)),
                ('f_io_cost', models.IntegerField(null=True)),
                ('f_object_alias', models.CharField(max_length=65, null=True)),
                ('f_object_instance', models.IntegerField(null=True)),
                ('f_object_name', models.CharField(max_length=30, null=True)),
                ('f_object_node', models.CharField(max_length=128, null=True)),
                ('f_object_owner', models.CharField(max_length=30, null=True)),
                ('f_object_type', models.CharField(max_length=30, null=True)),
                ('f_operation', models.CharField(max_length=30, null=True)),
                ('f_optimizer', models.CharField(max_length=255, null=True)),
                ('f_options', models.CharField(max_length=255, null=True)),
                ('f_other', models.IntegerField(null=True)),
                ('f_other_tag', models.CharField(max_length=255, null=True)),
                ('f_other_xml', models.BinaryField(null=True)),
                ('f_parent_id', models.IntegerField(null=True)),
                ('f_partition_id', models.IntegerField(null=True)),
                ('f_partition_start', models.CharField(max_length=255, null=True)),
                ('f_partition_stop', models.CharField(max_length=255, null=True)),
                ('f_plan_id', models.IntegerField(null=True)),
                ('f_position', models.IntegerField(null=True)),
                ('f_projection', models.TextField(null=True)),
                ('f_qblock_name', models.CharField(max_length=30, null=True)),
                ('f_remarks', models.TextField(null=True)),
                ('f_search_columns', models.IntegerField(null=True)),
                ('f_statement_id', models.CharField(max_length=30, null=True)),
                ('f_temp_space', models.IntegerField(null=True)),
                ('f_time', models.IntegerField(null=True)),
                ('f_timestamp', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'ISM_TOAD_PLAN_TABLE',
            },
        ),
    ]
