# Generated by Django 2.1.4 on 2018-12-31 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0029_auto_20181226_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncmodel',
            name='last_row_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
