# Generated by Django 2.1.4 on 2018-12-31 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0030_syncmodel_last_row_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncstatus',
            name='audit_result',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='syncstatus',
            name='audited_at',
            field=models.DateTimeField(null=True),
        ),
    ]
